version: '3'
services:
  react_app:
    image: react_app
    ports:
      - "81.94.159.128:8080:8080"
  fastapi:
    image: fastapi
    runtime: nvidia # uncomment on server with GPU
    command: uvicorn fastapp:app --reload --host "0.0.0.0" --port 8081
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
    ports:
      - "81.94.159.128:8081:8081"
  gpt_server:
    image: gpt_server
    stdin_open: true
    tty: true
    runtime: nvidia # uncomment on server with GPU
    command: gunicorn -w 1 --bind 0.0.0.0:8082 --timeout 3600 gpt_server:app
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONUNBUFFERED=1
      - MODEL_NAME=IlyaGusev/saiga2_13b_lora
      - BASE_MODEL_PATH=TheBloke/Llama-2-13B-fp16
    volumes:
      - /home/ubuntu/projects/volume:/user/volume
    ports:
      - 0.0.0.0:8082:8082
